from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    DEPENDENCY_NOT_FOUND = "DEPENDENCY_NOT_FOUND"
    MODEL_CONFIG_ERROR = "MODEL_CONFIG_ERROR"
    TARGET_UNREACHABLE = "TARGET_UNREACHABLE"
    HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"
    COMMAND_FAILED = "COMMAND_FAILED"
    ACTION_FAILED = "ACTION_FAILED"
    ASSERTION_FAILED = "ASSERTION_FAILED"
    VITEST_FAILED = "VITEST_FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    RISK_REQUIRES_APPROVAL = "RISK_REQUIRES_APPROVAL"
    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    RESUME_INVALID = "RESUME_INVALID"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"


class UiAgentError(RuntimeError):
    def __init__(self, code: ErrorCode, message: str, *, retryable: bool = False) -> None:
        super().__init__(message)
        self.code, self.retryable = code, retryable
