schema_version: 1
id: android.bilibili
platform: android
extends: ../../platforms/android.yaml
app:
  name: Bilibili
  package_name: tv.danmaku.bili
  launch_uri: tv.danmaku.bili
ui:
  free_markers: [免费观看, 免费]
  popup_prompts: [关闭普通信息弹窗]
  ad_prompts: [点击跳过广告或关闭广告]
